### ISSUE TITLE
Formatting display jamb

### ISSUE THREAD

**Issue by krote5k** [hexlet-basics/exercises-python#107]
"Именование _snake_ case\_."
только без пробела между _snake_ и case. Какой-то косяк в отображении форматирования.
https://ru.code-basics.com/languages/python/lessons/magic-numbers
В других тоже попадается подобное.

**Comment by zhabinka** [comment]
Я поправил - https://github.com/hexlet-basics/exercises-python/pull/109/commits/1a70b683d8bb4d4bdfe1f1c6bb9bc03273465545
Спасибо!

**Comment by krote5k** [comment]
Вам спасибо)
ещё: https://ru.code-basics.com/languages/python/lessons/naming
