### ISSUE TITLE
Пропущена буква "т" в слове "строки" в разделе 29 в теоретической части

### ISSUE THREAD

**Issue by OlexiyTest** [hexlet-basics/exercises-python#108]
Ожидаемый результат:
"Обращение к индексу за пределами строки приведёт к ошибке:"
Фактический результат:
"Обращение к индексу за пределами сроки приведёт к ошибке:"

**Comment by zhabinka** [comment]
Я поправил - https://github.com/hexlet-basics/exercises-python/pull/109/commits/6483864ced06a816ec3a604d72bb4fa80a1d3cc7
Спасибо!

**Comment by zhabinka** [comment]
Кстати, вы можете сами попробовать вносить изменения. Через pull request. Это ведь open source :)
