### ISSUE TITLE
Урок 13, проверка решения

### ISSUE THREAD

**Issue by antonjuice** [hexlet-basics/exercises-python#117]
На проверке принимается только одно решение:
`print("- Did Joffrey agree?\n" "- He did. He also said \"I love using \\n\".")`

Хотя решение 
`print('- Did Joffrey agree? \n- He did. He also said "I love using \\n".')`
соответствует условиям задачи и выводит аналогичный результат.

**Comment by Malcom1986** [comment]
Приветствую! В строке `'- Did Joffrey agree? \n- He did. He also said "I love using \\n".'` имеется лишний пробел между знаком вопроса и переводом строки. Если его убрать, то этот код тоже проходит тесты
