### ISSUE TITLE
Как бы я текст не писал текст в комманде print(), пишет что что-то не так

### ISSUE THREAD

**Issue by Overgeared-God-Grid** [hexlet-basics/exercises-python#173]
, только текст из теста выдавал правильный вариант, но разницы с моим нету

Код с текстом из вкладки тесты: print("Hello, World!")

Мой вариант: print("Hello, World!")

**Comment by fey** [comment]
@Overgeared-God-Grid Добрый день, проверьте сейчас. Должно работать.
