### ISSUE TITLE
"Выбор имени переменной" улучшить теорию для задания?

### ISSUE THREAD

**Issue by fey** [hexlet-basics/exercises-python#178]
https://ru.code-basics.com/languages/python/lessons/variables-naming

В задании урока требуется создать составную переменную (её имя состоит из нескольких слов). При этом не рассказывается, как правильно именовать переменные в Python (snake_case)

**Comment by fey** [comment]
https://github.com/hexlet-basics/exercises-python/blob/main/modules/30-variables/19-naming-style/description.ru.yml

Может быть урок про стиль именования поставить пораньше? :thinking:

**Comment by Alexion24** [comment]
@fey Актуальна ли ещё проблема? И правильно ли я понимаю, что нужно передвинуть 19-naming-style выше по директории и переименовать его и все остальные в соответствии с расположением новым?

**Comment by fey** [comment]
@Alexion24 тут сторонний контриьютер вряд ли сможет помочь. Нужно авторам курса решить, как сделать лучше, чтобы порядок подачи информации был верный

**Comment by fey** [comment]
```
короче, в этом уроке надо дать чуть больше примеров, в том числе показав составные имена
не говоря ничего про kebab case
и дальше в задании просто попросить сделать именование по такой же схеме с подчеркиванием
```

**Comment by Alexion24** [comment]
Принял в работу.
