### ISSUE TITLE
Урок 54. Неверная нумерация задач в разделе "Задание"

### ISSUE THREAD

**Issue by schepach** [hexlet-basics/exercises-python#216]
[**Урок 54. Python: Отрицание**](https://ru.code-basics.com/languages/python/lessons/logical-negation)
В разделе **"Задание"**  нумерация задач неверная. Два раза указано "1.", но в самом файле [**description.ru.yml**](https://github.com/hexlet-basics/exercises-python/blob/main/modules/45-logic/28-logical-negation/description.ru.yml) в ветке main нумерация указана корректно

**Comment by zhabinka** [comment]
Спасибо! Fixed – https://github.com/hexlet-basics/exercises-python/commit/6c191e2e7cf0a9c602d6ee41f6cbb042ca1369a8

**Comment by schepach** [comment]
@zhabinka  Рад был помочь 👍🏻
