### ISSUE TITLE
64 урок

### ISSUE THREAD

**Issue by Jmih228** [hexlet-basics/exercises-python#243]
Решил задание, но проверка не принимает,
"AttributeError: module 'index' has no attribute 'count_chars'"
хотя в другом интерпретаторе все работает.
`def letter_size_doesnt_matter(text,letter):
    text1 = text.lower()
    letter1 = letter.lower()
    index = 0
    count = 0
    while index < len(text):
        if text1[index] == letter1:
            count = count + 1
        index = index + 1
    return (count)`

![1](https://user-images.githubusercontent.com/109173366/178573105-4ba6a2ad-1d42-4601-b1cd-c9bda6491896.jpg)
![2](https://user-images.githubusercontent.com/109173366/178573172-b6afb4c7-2a0a-415d-9efc-989508f7e003.jpg)
![3](https://user-images.githubusercontent.com/109173366/178573215-bb750e7b-c620-4ecd-aff7-4b55e05fea5b.jpg)

**Comment by sgmdlt** [comment]
Добрый день. По заданию функцию нужно назвать `count_chars`
