### ISSUE TITLE
Exercise 44 - test passes with wrong solution

### ISSUE THREAD

**Issue by isbushcar** [hexlet-basics/exercises-python#248]
In exercise 44 expected solution is something like `print(len(text[4:15].strip()))`, but the test passes with the first slice value from 4 to 8 (e.g. `print(len(text[5:15].strip()))` or `print(len(text[8:15].strip()))`).
That seems to happen because of `\n` and `\t` symbols that get cut anyway

В упражнении 44 ожидаемое решение - что-то вроде `print(len(text[4:15].strip()))`, но тест проходит при указании первого значения слайса от 4 до 8 (например `print(len(text[5:15].strip()))` или `print(len(text[8:15].strip()))`).
Похоже это происходит из-за того, что символы `\n` и `\t` в любом случае обрезаются

**Comment by mjh-sakh** [comment]
The task has 3 parameters that may be checked: start index, end index, and application of the `strip`. It is not possible to check both indexes and `strip` together. The current task checks two things: end index and `strip` application. It feels optimal as it's more likely to do a mistake with the end index. Therefore it is advised to accept the possibility to have the start index wrong and keep the example as is and close the issue.
