### ISSUE TITLE
Exercise 39 - test passes with wrong (not full) solution

### ISSUE THREAD

**Issue by isbushcar** [hexlet-basics/exercises-python#249]
In exercise 39 test passes if user writes `print(round(random()))` as a solution.
That happens because that code returns 0 or 1 and test expects result to be >= 0 and <= 10.
Maybe it would be better to change task and ask user to write a code that prints random integer from 1 to 11.

В упражнении 39 тест проходит, если пользователь пишет `print(round(random()))` в качестве решения.
Это происходит, поскольку такой код возвращает 0 или 1, а тест ожидает, что результат будет >= 0 и <= 10.
Возможно было бы лучше изменить задачу и просить написать код, который выводит случайное число от 1 до 11.

**Comment by ashikov** [comment]
@sgmdlt, что думаешь?
