### ISSUE TITLE
Питон 3, Код-бейсикс

### ISSUE THREAD

**Issue by TAMADA611** [hexlet-basics/exercises-python#254]
Всем привет, немного недогнал, урок 47 - Параметры функций, на теории всё легко, но, когда надо было решить задачу, я может действительно тонкостей каких-то не понял, но по-моему решение учителя вообще никак не решает задачу или условия задачи заданы ну слишком туманно:
Код учителя: 
def truncate(text, length):
    # BEGIN
    result = f"{text[0:length]}..."
    return result
    # END
    
    Мой:
   def truncate(text, length):
      text = 'saaaaaas'
      lentgh = 4
      truncate2 = truncate(text, length)
      return truncate2
      
      Условия задачи:  Допишите функцию truncate(), которая обрезает переданную строку до указанного количества символов, добавляет в конце троеточие и возвращает получившуюся строку. Подобная логика часто используется на сайтах, чтобы отобразить длинный текст в сокращенном виде.

Функция принимает два параметра:

Строка, которую нужно обрезать
Число символов, которые нужно оставить
Пример того, как должна работать написанная вами функция:

# Передаём текст напрямую
# Обрезаем текст, оставляя 2 символа
truncate('hexlet', 2)  # 'he...'

# Через переменную
text = 'it works!'
# Обрезаем текст, оставляя 4 символа
truncate(text, 4)  # 'it w...'

**Comment by TAMADA611** [comment]
> 

То есть решение учителя вообще никаких данных не задаёт, даже параметры функции в решении это просто набор букв, даже не строка, я не говорю уже про заполненные переменные

**Comment by driverav** [comment]
Доброго дня! 

У меня всё верно работает в упражнении, проверьте на любом интерпретаторе python.
def truncate(text, length):
    # BEGIN
    result = f"{text[0:length]}..."
    return result
    # END

print(truncate('hello', 4))

ответ: hell...

**Comment by ashikov** [comment]
@emp7yhead

**Comment by dmitry-Ok** [comment]
hi) if you want, using this code. 
def truncate(text, length):   # Передаём текст напрямую # Обрезаем текст, оставляя 2(или сколько нужно) символа
     if len(text) <= length: #Можем воспользоваться if/else, мне проще так, хотя смысл такой же как f"{text[0:length]}..." где f - "{вырезаемый текст}", text[0:length] - наш аргумент (любое заданное слово) + количество символов для округления (задаем сами) + '...'
           return text # Затем то что получилось залаем для функции
     else:
         truncated_text = text[:length] + "..."
         return truncated_text
print(truncate("Russia", 2)) # В результате на экран выводится обработанное значение
