### ISSUE TITLE
Возможно тут ошибка?

### ISSUE THREAD

**Issue by driverav** [hexlet-basics/exercises-python#263]
![image](https://user-images.githubusercontent.com/117645899/202616642-e1f668a8-9111-4665-b4c2-42c8a49dc62a.png)

**Comment by ashikov** [comment]
Нет, ошибки тут нет. Чуть ниже есть описание: 

> Ветка `else` описана для второго условия, но не для первого. Поэтому вопросительное предложение становится `"normal"`

**Comment by driverav** [comment]
Благодарю Роман!

Надо было мне дочитать урок до конца, теперь всё встало на свои места. 😅

пт, 18 нояб. 2022 г. в 10:36, Roman Ashikov ***@***.***>:
