### ISSUE TITLE
Exercise 53

### ISSUE THREAD

**Issue by dzencot** [hexlet-basics/exercises-python#277]
https://github.com/hexlet-basics/exercises-python/blob/8be38782f18c72982d10862aa2746b7e7fda9d97/modules/45-logic/25-logical-operators/description.ru.yml#L8

В питоне можно написать 8 < x < 20, поэтому пример некорректный. Нужно переписать с другим примером.

**Comment by danokp** [comment]
Привет!

Готов придумать пример.
Как насчет такого:

`   Предположим, что сайт при регистрации требует, чтобы пароль был длиннее восьми символов и содержал хотя бы один из следующих специальных символов "(){}[]/*$#_@!?"...`

И далее расписать аналогично тому, как это реализовано сейчас.

**Comment by dzencot** [comment]
Привет! Хороший пример! Мне нравится)

**Comment by danokp** [comment]
Отлично!)
В течение этой недели проработаю пример и отправлю.
