### ISSUE TITLE
task 66, ссылка "Итерация" в блоке "Полезное" ведет на несуществующую страницу на вики

### ISSUE THREAD

**Issue by Bishamontess** [hexlet-basics/exercises-python#283]
![d8c6176fb18893bfde1e479337d0](https://user-images.githubusercontent.com/127602222/224491585-05ec9b3c-5151-4cdf-b567-0916b82c3a0b.png)

**Comment by emp7yhead** [comment]
Спасибо! Ссылку поправил.
