### ISSUE TITLE
Неверная ссылка на правило E225

### ISSUE THREAD

**Issue by trofimovelijah** [hexlet-basics/exercises-python#291]
На странице https://github.com/hexlet-basics/exercises-python/blob/main/modules/20-arithmetics/45-linting/description.ru.yml указана неверная ссылка на правило [**E225**](https://flake8.pycqa.org/en/latest/user/error-codes.html). 

![Выделение_942](https://github.com/hexlet-basics/exercises-python/assets/15788014/08147bfb-dfd3-4b6e-a097-108bf0b4c4c1)

**Comment by ssssank** [comment]
@sgmdlt глянь, пожалуйста
