### ISSUE TITLE
Задание 44

### ISSUE THREAD

**Issue by Atamurat-Ataniyazov** [hexlet-basics/exercises-python#324]
Ожидаемый результат:
Длина подстроки после применения strip() должна быть 7, так как после удаления пробелов останется 7 символов: "you play".

Ошибка:
В задании ошибочно указан диапазон среза [5:16]. Либо результат должен быть 8, а не 7. Или  для получения корректного результата необходимо изменить диапазон среза на [5:15].

**Comment by GrayOwls** [comment]
I am fixing

**Comment by sgmdlt** [comment]
Hello, this is not an issue. It's correctly stated here. It means natural counting, i.e. from 5th character in string up to and including 15.
