### ISSUE TITLE
Обновить ссылку для пулреквестов в уроке

### ISSUE THREAD

**Issue by Valeriya-Makhmutova** [hexlet-basics/exercises-python#327]
Ссылка для оставления пулреквестов (снизу) из [урока](https://code-basics.com/ru/languages/python/lessons/method-chain) ведёт на страницу с ошибкой (скрин прикрепила). Нужно заменить эту ссылку в уроке на актуальную.

![image](https://github.com/user-attachments/assets/1784f348-55b1-48b8-9331-3e5fdb6b395f)

**Comment by fey** [comment]
Fixed
