### ISSUE TITLE
Кодировка (Задание 15/63)

### ISSUE THREAD

**Issue by Kuroi-Kenshi** [hexlet-basics/exercises-python#49]
Ответ не соответствует заданию.

"Используя пример выше и найденную таблицу, выведите на экран (каждый на своей собственной строке) ~, ^ и %.

(Конечно, можно «обмануть» тесты и просто сделать print('~') и т.д., но так будет совсем неинтересно :)"

**Comment by astynax** [comment]
Что значит "ответ не соответствует заданию"?

**Comment by Kuroi-Kenshi** [comment]
В задании написано используя таблицу кодировки ASCII вывести на экран символы ~, ^ и %. А так же цитирую: "(Конечно, можно «обмануть» тесты и просто сделать print('~') и т.д., но так будет совсем неинтересно :)"

Соответственно правильным решением должно быть что-то типо этого:
print(chr(126))
print(chr(34))
print(chr(37))

Но это не работает и даже если использовать символ перевода строки \n.
А за правильный ответ засчитывает такой код: print('~\n^\n%')

**Comment by astynax** [comment]
Тесты не проверяют, что у вас там в коде записано. Поэтому никакого "ответ засчитывает такой код: print('~\n^\n%')" быть не может. Проверяется только то, что вы вывдоите на экран, любым способом.

**Comment by astynax** [comment]
Вот прямо сейчас проверил такой код:
```python
print(chr(120 + 6))
print(chr(90 + 4))
print(chr(30 + 7))
```
"Тесты пройдены"

**Comment by Kuroi-Kenshi** [comment]
Точно, я не правильно писал код для символа ^, таблица корявая какая то попалась. А зачем Вы складывали код для символов?

**Comment by astynax** [comment]
> А зачем Вы складывали код для символов?

Чтобы опказать, что даже такой код пройдёт тесты :)
