### ISSUE TITLE
Expressions in definitions

### ISSUE THREAD

**Issue by uzhas-sovka** [hexlet-basics/exercises-python#68]
https://ru.code-basics.com/languages/python/modules/variables/lessons/expressions

> Для перевода строчки можно использовать \n между выводом долларов и рублей.

В постановке задачи сначала выводятся доллары, потом, в другом месте ниже по тексту, после ещё минимум одной строки вычислений -- рубли. То есть вывод идёт в разных местах, двумя разными принтами, и он и так будет на разных строках, '\n' ставить просто некуда.

Одновременно '\n' ни к чему ставить отдельным принтом между текущими двумя, потому что даже между спанами в вёрстке страницы доп. строки нет.

**Comment by astynax** [comment]
В тексте не говорится, что `\n` нужно ставить "между принтами". И не говорится про "ещё одну строчку вычислений". Можно сначала всё посчитать, а потом всё вывести - одним вызовом `print` с разделением выводимых значений с помощью `\n`.

**Comment by astynax** [comment]
И "можно использовать" не означает "следует использовать".

**Comment by uzhas-sovka** [comment]
> переводит евро в доллары и выводит на экран. Затем полученное значение переводит в рубли и выводит на новой строчке.

Я эту фразу понял так.

1) переводим евро в доллары, присваиваем результат переменной, одна строка.
2) печатаем результат, вторая строка
3) переводим доллары из первой строки в рубли, третья строка
4) печатаем результат, четвёртая строка

То есть выводить надо два раза, на это есть прямое указание. Перечитал несколько раз, другой интерпретации не вижу :).

Не, понятно, что всё можно сделать в две строки, но я стараюсь делать дословно и не лезть со своими аэропланными подходами. И тогда возникает вопрос, куда приткнуть в таком конфиге '\n'
