### ISSUE TITLE
Typo in Python Lesson 59

### ISSUE THREAD

**Issue by svntmr** [hexlet-basics/exercises-python#69]
Насколько я помню, **Python к ЯП с динамической типизацией не относится**    
https://github.com/hexlet-basics/exercises-python/blob/master/modules/50-loops/25-edge-cases/description.ru.yml#L14

**Comment by astynax** [comment]
Python - язык со *сильной*, но тем не менее динамической типизацией.

Цитата из [Wiki](https://en.wikipedia.org/wiki/Python_(programming_language)):

> Python is dynamically typed...
