### ISSUE TITLE
Operators task

### ISSUE THREAD

**Issue by PC-Rat** [hexlet-basics/exercises-python#73]
print(6 - -81) the result isn't 87. I think 75 is more common.

**Comment by astynax** [comment]
Just checked it for sure:
```python
>>> print(6 - -81)
87
```

**Comment by astynax** [comment]
Goggle [agrees](https://www.google.com/search?hl=ru&q=6%20%2D%20%2D81) with me too.

**Comment by PC-Rat** [comment]
Oh, sorry. My bad.
