### ISSUE TITLE
if-else тесты не прошли

### ISSUE THREAD

**Issue by aleksnidzelskiy** [hexlet-basics/exercises-python#74]
Всем привет. В данном уроке тесты не проходят, хотя почему-то на https://repl.it/ проверил и моё решение должно быть верным.
https://ru.code-basics.com/languages/python/modules/logic/lessons/if-else

![image](https://user-images.githubusercontent.com/62075999/93721964-0d032000-fb9c-11ea-931d-f6d81a8bea58.png)

![image](https://user-images.githubusercontent.com/62075999/93721955-f5c43280-fb9b-11ea-8593-428c973e7956.png)

**Comment by astynax** [comment]
Ваш код неверно работает для адресов с протоколом "http://".
